"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$line_break\
$character"""

[directory]
truncate_to_repo = false

[character]
success_symbol = "[❯](blue)"
error_symbol = "[❯](blue)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style) "
style = "green"

[git_status]
style = "yellow"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "green"
